# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.Question'),
        ),
    ]
